### PR TITLE
Fix some Sidebery UI

### PR DESCRIPTION
**Pull request by DarkDipper**
Hi, I just change from default to developer edition browser, so I want to give ULTIMA a try, very nice so far. But there are some small bugs when I use it with sidebery, so I change some CSS in sidebery style for better experience to use.

| Bug                                                                                                                                                 | Fixed                                                                                                                                       |
| --------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------- |
| Gametreebug-ezgif-com-video-to-gif-converter | Fixed-ezgif-com-video-to-gif-converter-2 |
| Audio-icon-bug                                                             | Audio-icon-fixed                                                 |

Btw, I want to suggest a feature for sidebery's user. Option for when sidebar opens then the tab bar gone and vice versa. Or at least make private browser use the tab bar because sidebar gone by default.

When you use private window, if you use sidebery's sidebar, then it won't appear until you open it again. This is expected behavior from sidebery and firefox. And even though you use sidebery in the private window, it won't function correctly without container. So I would rather use the default vertical tab bar.

Before, I used to use a feature of sidebery that add prefix the title of the browser's window when sidebery's bar open and gone when sidebery's bar close. After that, I customize in useChrome file like below so to make it work.

```css
#main-window[titlepreface*="ULTIMA"] .tabbrowser-tab { /* ULTIMA New Tab */ 
  visibility: collapse !important;
}
```
I try to do the same thing, but not working so far. Can you consider it ?

Hope that's not confuse you too much 🙃.

### CODE REVIEW

**Comment by soulhotel** [comment]
For the fixed audio button placement, I welcome the change. But first..

The suggestion of using prefaces, while it does work well, there are some flaws:
- it clashes with userchrome toggler (x)
- scenarios where a website or such utilizes title prefaces (x)
- it would require additional layers of media-queries for scenarios where the user might not want the feature. And stacking media queries does have its limitations (x)
- it can take away the sidebar in scenarios where the user, uses, sidebery for history/bookmarks (x)

---

But it can still be done. I added a preference to about:config called  `ultima.tabs.vertical.onlyprivate`.

When set to true:
- vertical tabs will be disabled and you can use Sidebery as your vertical tab manager
- when you open a private window, the vertical tabs will automatically be visible
- while still being able to open Sidebery and use it freely

https://github.com/soulhotel/FF-ULTIMA/assets/155501797/03ddcfea-e594-45df-943a-1ec0292f6e9f

---

This is ready for the 1.7.9 update. But this update holds a lot of changes, and  waiting 1 more day to see if I find any bugs.

Regardless, I'd like for you to try the update and tell me how  `ultima.tabs.vertical.onlyprivate` feels.

You can view the change log on the main.update.branch: [change-log](https://github.com/soulhotel/FF-ULTIMA/blob/main.update.branch/doc/change-log.md)

You can download the main.update.branch source: [or click here](https://github.com/soulhotel/FF-ULTIMA/archive/refs/heads/main.update.branch.zip)

**Comment by DarkDipper** [comment]
I think you miss about my fixed tabs trees too (The first two gif, I guess it not load ?) beside the audio icon.

I have tested 1.7.9 ver. `ultima.tabs.vertical.onlyprivate` work as expected. But can you allow sidebar auto hide even though `ultima.tabs.vertical.hide=true/false` or at least `ultima.tabs.vertical.onlyprivate=true` ?. I expect sidebar auto hide work but seem like it only work when `ultima.tabs.vertical.hide=true`.

Also while I testing, I have tried some theme like [Bluegreylight](https://addons.mozilla.org/en-US/firefox/addon/bluegreylight/), Default Dark theme... it cause some wrong color, I list below:

- [Bluegreylight](https://addons.mozilla.org/en-US/firefox/addon/bluegreylight/), Default Dark theme( I think any dark theme): Color of extension button not affect so the button very hard to see
- [Firefox Alpenglow](https://addons.mozilla.org/en-US/firefox/addon/firefox-alpenglow/): The vertical bar and sidebar's background completely white
- System theme - auto - Dark theme: The background color of close window button is black not red.

I guess theme gradient add-on not compatible ?

**Comment by soulhotel** [comment]
Yeah, I noticed the fixed tab trees its a good idea, also I removed the limit for the sidebar (in the main.update.branch).

Addon themes are tricky.. Every theme relies on its own color declaration which is applied to existing browser variables around the Firefox UI.

Some addon theme creators may use `--lwt-accent-color` as their primary color, others might use `--toolbar-bg-color` as their primary color. Because of that, the variables are not used consistently when comparing different addon themes against each other (see below).

Because of this, its almost impossible to get every single theme to match the userChrome theme itself. It can be done if you find a theme you like, then change the userChrome theme's color's around. But 1 theme may not match like another theme. This was actually my biggest frustration when deciding to structure the code to let addon themes override it. But I did it in such a way that many themes (not all, sadly) can still fit in.


| Example   | image   |
|----|------------------|
| 1  |     |
| 2  |   |
| 3  |   |

Notice how the first two themes below fit almost perfectly, compared to the alpenglow theme. if i were to change ff ultimas code to match the alpenglow theme, then almost every other theme in the store would not look right. Some gradient themes work, even the animated navigation bar themes, but it really depends on what variables the creators used to structure the theme itself.

**Comment by soulhotel** [comment]
I appreciate the feedback and suggestions so far. I'll merge this in a bit, I have to take care of something first.

**Comment by soulhotel** [comment]
Alright merged,

Im going to look and see what I can do about lwt add-on theme colors, I really dont think I'll find a "fix-all" solution because of everything I stated above. Maybe using color mix could be a fix, maybe not..

**Pull request merged**
