### PR TITLE
Re-enables auto-hiding!

### PR DESCRIPTION
**Pull request by tthornton3-chwy**
Hey hey hey! Hope all is well over there :D

I got sad by the lack of auto-hiding, and decided I wanted to frustrate/experiment myself getting it working again haha.

I am definitely NOT recommending we merge this in, but if Mozilla never adds in native support for this, this could work :P

I used this: https://github.com/xiaoxiaoflood/firefox-scripts?tab=readme-ov-file#instructions

Then sidebarAutoHide.uc.js:19 is where the meat and potatoes are. Essentially we stop this: https://searchfox.org/mozilla-central/source/browser/components/sidebar/SidebarState.sys.mjs#293 from happening, which ultimately is what is making us sad.

All-in-all this was a fun lil experiment, and anyone who is literally dying without this currently could potentially use this in the mean time lol.

### CODE REVIEW

**Comment by soulhotel** [comment]
Yep, using js crossed my mind too. Was hoping that this change wouldn't make it into Default and Dev Edition, but since its a result of the new sidebar splitter it's definitely here to stay, until they hopefully figure out auto-hiding themselves.

I'm turned off by the idea of forcing people to setup/maintain autoconfig, but for You and Others with the patience to set it up, I can just have the old style (collapsed icons) available through "nightly-override". And everyone else will just have to deal with the "completely hidden" auto-hiding, when their Browsers reach this 135 update.

Thank you for putting this all together. I think this is a good merge. Will look over it again in the morning.

**Comment by tthornton3-chwy** [comment]
Oh I 100% agree haha, I hate the thought of needing people to set autoconfig up 🥲 this theme does so much without needing to do it, which is a testament on its own, so to have to do it now to get this to work hurts haha. 
But yeah, I agree, the option may be nice for those who hate change/loves the auto-collapsing. Technically the config I brought in was the "extension+script" package, if we do wanna merge this sucker we could remove a few files to narrow it down to just scripts 🤔

**Comment by soulhotel** [comment]
Right, I was honestly thinking about leaving it, hoping I could somehow override mozilla's extension permissions for this [FF Ultima Companion](https://github.com/soulhotel/FF-ULTIMA/tree/Companions) I made, it can read preferences for the theme, but lacks the permission to modify them. I asked chatgpt if it could be done in multiple ways with autoconfig, but don't think it's possible..

https://github.com/user-attachments/assets/67a1a0a0-3d93-4e2e-a0ad-aaae76d14bef

But also, since this is a "theme with too many options", maybe You or someone else might find the extension module useful in the future, honestly, your call. I can always just link the source as a separate download link for anyone that wants the autoconfig files included.

**Comment by tthornton3-chwy** [comment]
Oh interesting! I think that's a great idea! We definitely can do this with autoconfig, but the path of least resistance might be to re-create it using a script, similar to the userChrome Manager they got. Hmmmm 🤔

**Pull request merged**
